// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUnszYKw5mY-EFOVMYK2W1gLcVQmhw-RM',
    appId: '1:1003014358536:web:b2bf04cc0c2b8ee270b3bd',
    messagingSenderId: '1003014358536',
    projectId: 'par-optima',
    authDomain: 'par-optima.firebaseapp.com',
    databaseURL: 'https://par-optima-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'par-optima.firebasestorage.app',
    measurementId: 'G-2VDVJ2PHSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArzxPSPUNb6kuct9dnFPPnGJ0zD2VVvKI',
    appId: '1:1003014358536:android:b06e87f092ca5f3f70b3bd',
    messagingSenderId: '1003014358536',
    projectId: 'par-optima',
    databaseURL: 'https://par-optima-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'par-optima.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcaLSJKDP9BI1CxT0OuZUrTI26nJ4Mhgk',
    appId: '1:1003014358536:ios:ccbbb0f6aaec0f7a70b3bd',
    messagingSenderId: '1003014358536',
    projectId: 'par-optima',
    databaseURL: 'https://par-optima-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'par-optima.firebasestorage.app',
    iosBundleId: 'com.example.parOptima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcaLSJKDP9BI1CxT0OuZUrTI26nJ4Mhgk',
    appId: '1:1003014358536:ios:ccbbb0f6aaec0f7a70b3bd',
    messagingSenderId: '1003014358536',
    projectId: 'par-optima',
    databaseURL: 'https://par-optima-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'par-optima.firebasestorage.app',
    iosBundleId: 'com.example.parOptima',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUnszYKw5mY-EFOVMYK2W1gLcVQmhw-RM',
    appId: '1:1003014358536:web:d28140652a6a93d770b3bd',
    messagingSenderId: '1003014358536',
    projectId: 'par-optima',
    authDomain: 'par-optima.firebaseapp.com',
    databaseURL: 'https://par-optima-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'par-optima.firebasestorage.app',
    measurementId: 'G-G2955HFYTF',
  );
}
