import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:provider/provider.dart';

// 🛑 Local Imports - Ensure these paths are correct in your project
import 'src/screens/login.dart';
import 'src/screens/patient_interface.dart';
import 'src/services/communication_service.dart'; // Handles Agora RtcEngine
import 'src/services/patient_data_service.dart'; // Handles Firebase RTDB
import 'firebase_options.dart'; // Auto-generated by flutterfire configure
import '../src/screens/robot_interface.dart';

Future<void> main() async {
  // Always call this first when using plugins
  WidgetsFlutterBinding.ensureInitialized();

  // 1. FIREBASE INITIALIZATION
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint("Firebase Initialized.");
  } catch (e) {
    debugPrint(
      '🛑 ERROR: Firebase initialization failed. Did you run flutterfire configure? Error: $e',
    );
  }

  // 2. AGORA ENGINE INITIALIZATION
  final commService = CommunicationService();
  try {
    await commService.initializeEngine();
    debugPrint("Agora Engine Initialized.");
  } catch (e) {
    debugPrint(
      '🛑 ERROR: Agora initialization failed. Check App ID/Permissions. Error: $e',
    );
  }

  3. AUTO-LOGIN CHECK
  bool isLoggedIn = false;
  try {
    final prefs = await SharedPreferences.getInstance();
    // 'isLoggedIn' flag must be set to true upon successful login in LoginPage
    isLoggedIn = prefs.getBool('isLoggedIn') ?? false;
  } catch (e) {
    debugPrint('Error accessing SharedPreferences for login check: $e');
  }

  4. LAUNCH APPLICATION
  runApp(
    MultiProvider(
      providers: [
        // Provides real-time data from Firebase to the UI
        ChangeNotifierProvider<PatientDataService>(
          create: (_) => PatientDataService(),
        ),
        // Provides the configured Agora service for video calls
        Provider<CommunicationService>.value(value: commService),
      ],
      child: ParOptimaApp(isLoggedIn: isLoggedIn),
    ),
  );





class ParOptimaApp extends StatelessWidget {
  final bool isLoggedIn;

  const ParOptimaApp({super.key, required this.isLoggedIn});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PAR Optima Prototype',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        // Ensure fonts/theming are consistent across the app
      ),
      // Use the login status to determine the initial screen
      home: isLoggedIn ? const PatientInterface() : LoginPage(),
    );
  }

// void main() {
//   runApp(MaterialApp(
//     debugShowCheckedModeBanner: false,
//     home: RobotInterface(), // This tells the app to start on the Login Page
//   ));
// }
}

